### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by KoniHD** [aldreth/google-fit-to-garmin#65]
Hello there,

please excuse if I am being rude here I'm quite new to Github :)
I was just wondering after reading the [README.md](https://github.com/aldreth/google-fit-to-garmin/blob/main/README.md) what this repo actually does? I mean it looks like a pretty complicated setup especially focusing on contributions. However, I would be interested in the usage of the name of this repo.
In other words is there a way to syn google fit to garmin or the other way around with this repo? (At least that is what I was hoping for reading the name :smiley:) Or is this an unfinished clone from this [repo](https://github.com/actions/typescript-action)? In that case I might be interested in making this work :grinning: with my own project 

Best

**Comment by aldreth** [comment]
Hi there

That was what I was trying to do, but I don't think I got anywhere I'm afraid!
